name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install lint tools
        run: |
          pip install flake8
          echo "Linting app..."
          flake8 app || true

      - name: Build Docker image
        run: |
          docker build -t hello-portfolio:ci .
